<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>astra-server</AssemblyName>
    <RootNamespace>Astra.Server</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <UserSecretsId>astra-server</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == ''">
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Astra.Core\Astra.Core.csproj" />
    <ProjectReference Include="..\Astra.Data\Astra.Data.csproj" />
    <ProjectReference Include="..\Astra.Providers\Astra.Providers.csproj" />
    <ProjectReference Include="..\Astra.Gateway\Astra.Gateway.csproj" />
    <ProjectReference Include="..\Astra.Clients\Astra.Clients.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Astra.Server.IntegrationTests" />
  </ItemGroup>
</Project>
